######################################################################
# Automatically generated by qmake (2.01a) Fri Jun 4 20:37:58 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
