######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 8 13:39:40 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
