######################################################################
# Automatically generated by qmake (2.01a) Fri Jun 4 21:22:53 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mylistbands.h
FORMS += mylistbands.ui
SOURCES += main.cpp mylistbands.cpp
