<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />

  <meta name="title" content="zf :: example" />
  <meta name="author" content="Nycholas de Oliveira e Oliveira - nycholas@gmail.com" />
  <meta name="description" content="zf :: example" />
  <meta name="keywords" content="php zend framework example" />
  <meta name="distribution" content="global" />
  <meta name="copyright" content="Copyright (C) 2010 by Nycholas de Oliveira e Oliveira - nycholas@gmail.com" />

  <link href="/static/image/e.ico" rel="shortcut icon" type="image/x-icon" />
  <link href="/static/style/base.css" rel="stylesheet" type="text/css" charset="utf-8" />
  <noscript></noscript>

  <title>zf :: example</title>
</head>
<body>

<h1 style="padding: 20px; padding-bottom: 30px;">
  zf :: example
</h1>

<div style="padding: 10px; text-align: right;"><a href="<?php echo $this->url(array('controller' => 'notebook'), 'default', true) ?>">Notebook</a></div>

<?php echo $this->layout()->content; ?>

</body>
</html>