######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 8 13:38:45 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mylistbands.h
FORMS += mylistbands.ui
SOURCES += main.cpp mylistbands.cpp
