######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 8 13:39:23 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += mylistbands.ui
SOURCES += main.cpp
