######################################################################
# Automatically generated by qmake (2.01a) Fri Jun 4 21:16:29 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += mylistbands.ui
SOURCES += main.cpp
