# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mylistbands_ui.ui'
#
# Created: Wed Aug 19 18:16:25 2009
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MyListBands(object):
    def setupUi(self, MyListBands):
        MyListBands.setObjectName("MyListBands")
        MyListBands.resize(380, 389)
        self.gridWidget = QtGui.QWidget(MyListBands)
        self.gridWidget.setGeometry(QtCore.QRect(9, 9, 361, 371))
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.gridWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtGui.QLabel(self.gridWidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.listWidget = QtGui.QListWidget(self.gridWidget)
        self.listWidget.setObjectName("listWidget")
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        self.gridLayout_2.addWidget(self.listWidget, 1, 0, 1, 1)
        self.pbExit = QtGui.QPushButton(self.gridWidget)
        self.pbExit.setObjectName("pbExit")
        self.gridLayout_2.addWidget(self.pbExit, 2, 0, 1, 1)

        self.retranslateUi(MyListBands)
        QtCore.QObject.connect(self.pbExit, QtCore.SIGNAL("clicked()"), MyListBands.close)
        QtCore.QMetaObject.connectSlotsByName(MyListBands)

    def retranslateUi(self, MyListBands):
        MyListBands.setWindowTitle(QtGui.QApplication.translate("MyListBands", "My List Band\'s", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MyListBands", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans Mono\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:18px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#aa0000;\">My List Band\'s</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        self.listWidget.item(0).setText(QtGui.QApplication.translate("MyListBands", "Aerosmith", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(1).setText(QtGui.QApplication.translate("MyListBands", "AC/DC", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(2).setText(QtGui.QApplication.translate("MyListBands", "After Forever", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(3).setText(QtGui.QApplication.translate("MyListBands", "Airboune", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(4).setText(QtGui.QApplication.translate("MyListBands", "Alice In Chains", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(5).setText(QtGui.QApplication.translate("MyListBands", "The Allman Brothers Band", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(6).setText(QtGui.QApplication.translate("MyListBands", "Angra", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(7).setText(QtGui.QApplication.translate("MyListBands", "Audioslave", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(8).setText(QtGui.QApplication.translate("MyListBands", "Avantasia", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(9).setText(QtGui.QApplication.translate("MyListBands", "Baltazares", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(10).setText(QtGui.QApplication.translate("MyListBands", "Baranga", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(11).setText(QtGui.QApplication.translate("MyListBands", "The Black Crowes", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(12).setText(QtGui.QApplication.translate("MyListBands", "Black Label Society", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(13).setText(QtGui.QApplication.translate("MyListBands", "Black Sabbath", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(14).setText(QtGui.QApplication.translate("MyListBands", "Blitzkid", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(15).setText(QtGui.QApplication.translate("MyListBands", "Brasileiros S/A", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(16).setText(QtGui.QApplication.translate("MyListBands", "Bruce Dickinson", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(17).setText(QtGui.QApplication.translate("MyListBands", "Cachorro Grande", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(18).setText(QtGui.QApplication.translate("MyListBands", "Carey, Bell, Billy Branch, James Cotton", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(19).setText(QtGui.QApplication.translate("MyListBands", "Celso Blues Boy", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(20).setText(QtGui.QApplication.translate("MyListBands", "Chicago Blues Harmonica Project", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(21).setText(QtGui.QApplication.translate("MyListBands", "Chimaira", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(22).setText(QtGui.QApplication.translate("MyListBands", "Chris Cornell", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(23).setText(QtGui.QApplication.translate("MyListBands", "Cry of Love", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(24).setText(QtGui.QApplication.translate("MyListBands", "Death", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(25).setText(QtGui.QApplication.translate("MyListBands", "Deep Purple", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(26).setText(QtGui.QApplication.translate("MyListBands", "Dio", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(27).setText(QtGui.QApplication.translate("MyListBands", "Dirty Sweet", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(28).setText(QtGui.QApplication.translate("MyListBands", "Disturbed", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(29).setText(QtGui.QApplication.translate("MyListBands", "Dog Eat Dog", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(30).setText(QtGui.QApplication.translate("MyListBands", "The Doors", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(31).setText(QtGui.QApplication.translate("MyListBands", "Dream Theater", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(32).setText(QtGui.QApplication.translate("MyListBands", "Driver By Truckers", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(33).setText(QtGui.QApplication.translate("MyListBands", "Edu Ardanuy", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(34).setText(QtGui.QApplication.translate("MyListBands", "Foo Fighters", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(35).setText(QtGui.QApplication.translate("MyListBands", "Garotos Podres", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(36).setText(QtGui.QApplication.translate("MyListBands", "Glenn Hughes", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(37).setText(QtGui.QApplication.translate("MyListBands", "Gnarls Barkley", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(38).setText(QtGui.QApplication.translate("MyListBands", "Godsmack", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(39).setText(QtGui.QApplication.translate("MyListBands", "Gramofocas", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(40).setText(QtGui.QApplication.translate("MyListBands", "Heaven and Hell", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(41).setText(QtGui.QApplication.translate("MyListBands", "Iced Earth", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(42).setText(QtGui.QApplication.translate("MyListBands", "Incubus", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(43).setText(QtGui.QApplication.translate("MyListBands", "Iron Maiden", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(44).setText(QtGui.QApplication.translate("MyListBands", "Jaded Sun", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(45).setText(QtGui.QApplication.translate("MyListBands", "James Cotton & Charlie Haden", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(46).setText(QtGui.QApplication.translate("MyListBands", "Jim Morrison", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(47).setText(QtGui.QApplication.translate("MyListBands", "Jimi Hendrix", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(48).setText(QtGui.QApplication.translate("MyListBands", "The Johnny O. Band", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(49).setText(QtGui.QApplication.translate("MyListBands", "Judas Priest", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(50).setText(QtGui.QApplication.translate("MyListBands", "Kiss", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(51).setText(QtGui.QApplication.translate("MyListBands", "Led Zeppelin", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(52).setText(QtGui.QApplication.translate("MyListBands", "Living Colour", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(53).setText(QtGui.QApplication.translate("MyListBands", "Lynyrd Skynyrd", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(54).setText(QtGui.QApplication.translate("MyListBands", "Matanza", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(55).setText(QtGui.QApplication.translate("MyListBands", "Megadeath", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(56).setText(QtGui.QApplication.translate("MyListBands", "Metallica", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(57).setText(QtGui.QApplication.translate("MyListBands", "Misfits", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(58).setText(QtGui.QApplication.translate("MyListBands", "Motorocker", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(59).setText(QtGui.QApplication.translate("MyListBands", "Motörhead", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(60).setText(QtGui.QApplication.translate("MyListBands", "Murderdolls", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(61).setText(QtGui.QApplication.translate("MyListBands", "Nickelback", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(62).setText(QtGui.QApplication.translate("MyListBands", "Northern Kings", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(63).setText(QtGui.QApplication.translate("MyListBands", "O Rappa", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(64).setText(QtGui.QApplication.translate("MyListBands", "Ozzy Osbourne", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(65).setText(QtGui.QApplication.translate("MyListBands", "Pantera", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(66).setText(QtGui.QApplication.translate("MyListBands", "The Parlor Mob", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(67).setText(QtGui.QApplication.translate("MyListBands", "Planet Hemp", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(68).setText(QtGui.QApplication.translate("MyListBands", "Radiohead", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(69).setText(QtGui.QApplication.translate("MyListBands", "Ratos de Porão", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(70).setText(QtGui.QApplication.translate("MyListBands", "Red Hot Chili Peppers", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(71).setText(QtGui.QApplication.translate("MyListBands", "Rock Rocket", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(72).setText(QtGui.QApplication.translate("MyListBands", "Scott Weiland", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(73).setText(QtGui.QApplication.translate("MyListBands", "Seal", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(74).setText(QtGui.QApplication.translate("MyListBands", "Shaman", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(75).setText(QtGui.QApplication.translate("MyListBands", "Sonic Youth", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(76).setText(QtGui.QApplication.translate("MyListBands", "Soundgarden", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(77).setText(QtGui.QApplication.translate("MyListBands", "Steel Dragon", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(78).setText(QtGui.QApplication.translate("MyListBands", "Stevie Ray Vaughan", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(79).setText(QtGui.QApplication.translate("MyListBands", "Stone Temple Pilots", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(80).setText(QtGui.QApplication.translate("MyListBands", "Temple Of The Dog", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(81).setText(QtGui.QApplication.translate("MyListBands", "Van Halen", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(82).setText(QtGui.QApplication.translate("MyListBands", "Velhas Vírgens", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(83).setText(QtGui.QApplication.translate("MyListBands", "Wolfmother", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(84).setText(QtGui.QApplication.translate("MyListBands", "Zakk Wylde", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(85).setText(QtGui.QApplication.translate("MyListBands", "Zumbis do Espaço", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(86).setText(QtGui.QApplication.translate("MyListBands", "ZZ Top", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.pbExit.setText(QtGui.QApplication.translate("MyListBands", "Exit", None, QtGui.QApplication.UnicodeUTF8))

